### ISSUE TITLE
ARM64 support available for the latest version

### ISSUE THREAD

**Issue by danktankk** [RoastSlav/quickdrop#10]
the following docker-compose.yml will pull down the arm64 image instead of arm64 for those that use arm architacture.

enjoy

```
networks:
  proxy:
    external: true

services:
  quickdrop:
    image: danktankk/quickdrop:arm64
    container_name: quickdrop
    networks:
      - proxy
    ports:
      - "8080:8080"
    volumes:
      - ./db:/app/db
      - ./log:/app/log
      - ./files:/app/files
    restart: unless-stopped
```

tested working.
