### ISSUE TITLE
Error Docker Container

### ISSUE THREAD

**Issue by Schnurp** [RoastSlav/quickdrop#35]
Every Container I start as a Project, greater than Version 1.4.1 runs in an Error with very strange Docker Behaviour. Version 1.4.1 runs fine, without problems. 

I run the Docker project on a Synology NAS. 

Does anyone else also have problems?

I also noticed, that Version 1.4.1 has an image size of 492MB and every newer version only has about 179MB or something like that.

**Comment by Schnurp** [comment]
That would be great. Thank you very much for your work!

I would like tosupport you with a better error message but I dont really have one. Docker / Container Manager on Synology reacts very strange with error and you can´t really stop the container after that.

This is my docker YAML-Config:

`services:
  quickdrop:
    image: roastslav/quickdrop:v1.4.1
    container_name: QuickDrop
    healthcheck:
      test: timeout 10s bash -c ':> /dev/tcp/127.0.0.1/8080' || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    ports:
     - 8487:8080
    volumes:
    - /volume1/docker/quickdrop/app/db:/app/db:rw
    - /volume1/docker/quickdrop/app/files:/app/files:rw
    - /volume1/docker/quickdrop/app/log:/app/log:rw
    - /volume1/docker/quickdrop/app/application.properties:/app/application.properties:rw
    restart: on-failure:5
    
networks:
    default:
        external:
            name: QDNet`

**Comment by issafram** [comment]
My first thought is that it could be your health check that is failing.  The reason being that the smaller image size is due to using Alpine as the base.  Which, if I recall correctly, doesn't include bash.

Try testing by removing the health check.

I can test a little bit later today to see if it could be something else.  But start with my suggestion first.

**Comment by Schnurp** [comment]
YES!

It was the health check! 

Error is resolved! Thank you very much for yout quick help!

**Comment by issafram** [comment]
> YES!
> 
> It was the health check!
> 
> Error is resolved! Thank you very much for yout quick help!

no problem
@Schnurp please share your updated health check, incase someone else looks at this in the future.

**Comment by Schnurp** [comment]
Updated YAML without healthcheck:


```
services:
  quickdrop:
    image: roastslav/quickdrop:v1.4.1
    container_name: QuickDrop
    ports:
     - 8487:8080
    volumes:
    - /volume1/docker/quickdrop/app/db:/app/db:rw
    - /volume1/docker/quickdrop/app/files:/app/files:rw
    - /volume1/docker/quickdrop/app/log:/app/log:rw
    - /volume1/docker/quickdrop/app/application.properties:/app/application.properties:rw
    restart: on-failure:5
    
networks:
    default:
        external:
            name: QDNet
```
